version: '3'
services:
  typecho:
    image: ghcr.io/imkero/typecho-apache:latest
    container_name: typecho
    ports:
      - 127.0.0.1:10080:80
    volumes:
      - ./usr/uploads:/var/www/html/usr/uploads
      - ./db:/var/volume/db
      - ./usr/themes/ueno/style.css:/var/www/html/usr/themes/ueno/style.css
      - ./config.inc.php:/var/www/html/config.inc.php:ro
      - /dev/null:/var/www/html/install.php:ro
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
