version: '3'
services:
  typecho:
    image: ghcr.io/imkero/typecho-apache:latest
    container_name: typecho
    ports:
      - 127.0.0.1:10080:80
    volumes:
      - ./usr/uploads:/var/www/html/usr/uploads
      - ./db:/var/volume/db
    restart: unless-stopped
