# fly.toml app configuration file generated for kero-blog on 2023-12-10T07:01:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kero-blog"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source="typecho"
  destination="/mnt/volume"
  initial_size = "1GB"
  auto_extend_size_threshold = 75
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "16GB"

